In [ ]:
from google.colab import files
uploaded = files.upload()

# World Happiness Data Analysis

## Project Overview
This project explores the **World Happiness dataset** to understand the factors that influence happiness across different countries.

Using Python and data analysis techniques, we will:

- Explore the structure of the dataset
- Identify missing values
- Clean the data
- Perform exploratory data analysis (EDA)
- Visualize relationships between variables
- Extract meaningful insights

The goal of this analysis is to understand which factors most strongly influence happiness levels around the world.

## Dataset Description

The dataset contains country-level indicators related to happiness and quality of life.

### Key Features

- **Country name** – Name of the country
- **year** – Year of observation
- **Life Ladder** – Happiness score
- **Log GDP per capita** – Economic prosperity
- **Social support** – Perceived social support
- **Healthy life expectancy at birth** – Health indicator
- **Freedom to make life choices** – Personal freedom
- **Generosity** – Measure of generosity
- **Perceptions of corruption** – Public perception of corruption

These variables help explain differences in happiness levels between countries.

In [47]:
# Import important libraries for our data analysis

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("World Happiness Report 2005-2021.csv")
df.head()

,Country_name,Life Ladder,Log GDP per capita,Social_support,Healthy life expectancy at birth,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption,Positive affect,Negative affect,Confidence in national government
0,Afghanistan,3.723590,7.302574,0.450662,50.500000,0.718114,0.173169,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,4.401778,7.472446,0.552308,50.799999,0.678896,0.195469,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,4.758381,7.579183,0.539075,51.099998,0.600127,0.125859,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,3.831719,7.552006,0.521104,51.400002,0.495901,0.167723,0.731109,0.479835,0.267175,0.307386
4,Albania,4.639548,9.454930,0.637698,69.050003,0.749611,-0.028629,0.876135,0.547240,0.333884,0.457738


## Understanding the Dataset

Before performing analysis, we first explore the structure of the dataset.

We will check:

- Number of rows and columns
- Column names
- Data types
- Missing values

In [ ]:
# Inorder to knoow the number of rows and columns in our dataset
df.shape

In [ ]:
# Show column names
df.columns

In [ ]:
# Show information about dataset structure , datatype of each columns ....
df.info()

 **Check for Missing Data**

In [ ]:
# let us Count missing values in each column as we see the column of confidence in national government has many nulls so we need to handle those missing values well.
df.isnull().sum()

In [ ]:
# Total missing values in the whole dataset
df.isnull().sum().sum()

In [ ]:
(df.isnull().sum() / len(df)) * 100

**Since our total missing values in our data set is only 17 , we can easily remove them or replace them with their column average value . For my case replacing with the column average is better option , rather than loosing our row datas .**

In [ ]:
df.fillna(df.mean(numeric_only=True), inplace=True)
# Now we have replaced all our missing datas with the column average.

In [ ]:
df["Confidence in national government"].fillna(
    df["Confidence in national government"].mean(),
    inplace=True
)

In [ ]:
# lets check if we have really replaced all missing datas
df.isnull().sum().sum()

In [ ]:
# We need to import sqlite3 to create and interact with a SQL database
import sqlite3
# Import matplotlib for visualization
import matplotlib.pyplot as plt

In [ ]:
# Create a connection to a SQLite database
conn = sqlite3.connect("happiness.db")

# Store the dataframe inside the database as a table
df.to_sql("happiness", conn, if_exists="replace", index=False)

**Top 10 Happiest Countries**

In [ ]:
# Calculate average happiness score by country

top_countries = (
    df.groupby("Country_name")["Life Ladder"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(10,6))

sns.barplot(
    x=top_countries.values,
    y=top_countries.index
)

plt.title("Top 10 Happiest Countries in the World")
plt.xlabel("Average Happiness Score")
plt.ylabel("Country")

plt.show()

In [44]:
pd.read_sql("""
SELECT Country_name, AVG("Life Ladder") AS avg_happiness
FROM happiness
GROUP BY Country_name
ORDER BY avg_happiness DESC
LIMIT 10;
""", conn)

  Country_name  avg_happiness
0      Austria       7.162830
1      Belgium       6.805449
2       Brazil       6.515243
3       Belize       6.203146
4    Argentina       6.031193
5      Bahrain       5.635653
6      Bolivia       5.596464
7      Belarus       5.576553
8      Algeria       5.236032
9       Bhutan       5.196599

**Top 10 countries With Highest GDP**

In [ ]:
pd.read_sql("""
SELECT Country_name, AVG("Log GDP per capita") AS "Avg Log GDP per capita"
FROM happiness
GROUP BY Country_name
ORDER BY "Log GDP per capita" DESC
LIMIT 10
""", conn)

**Top 10 Countries With Lowest Happiness**

In [ ]:
pd.read_sql("""
SELECT Country_name, Avg("Life Ladder") As Avg_life_ladder
FROM happiness
Group BY Country_name
ORDER BY "Life Ladder" ASC
LIMIT 10
""", conn)

**Top 10 Countries With Highest Freedom**

In [ ]:
pd.read_sql("""
SELECT Country_name, Avg(Freedom_to_make_life_choices) As AVG_Freedom
FROM happiness
GROUP BY Country_name
ORDER BY Freedom_to_make_life_choices DESC
LIMIT 10
""", conn)

**Top 10 Countries With Highest Social Support**

In [ ]:
pd.read_sql("""
SELECT Country_name, AVG(Social_support) AS Avg_Social_Support
FROM happiness
Group by Country_name
ORDER BY Social_support DESC
LIMIT 10
""", conn)

**Top 10 Countries With Highest Life Expectancy**

In [ ]:
pd.read_sql("""
SELECT Country_name, Avg("Healthy life expectancy at birth") AS AVG_life_expectancy
FROM happiness
GROUP BY Country_name
ORDER BY "Healthy life expectancy at birth" DESC
LIMIT 10
""", conn)

**Top 10 Countries With Highest Corruption Perception:**

In [ ]:
pd.read_sql("""
SELECT Country_name, AVG(Perceptions_of_corruption) AS "Avg perceptyion of corruption"
FROM happiness
Group BY Country_name
ORDER BY Perceptions_of_corruption DESC
LIMIT 10
""", conn)

**Average Happiness Score**

In [ ]:
pd.read_sql("""
SELECT AVG("Life Ladder") AS average_happiness
FROM happiness
""", conn)

**Top 10 Countries With Highest Positive Emotions**

In [ ]:
pd.read_sql("""
SELECT Country_name, "Positive affect"
FROM happiness
GROUP BY
ORDER BY "Positive affect" DESC
LIMIT 10
""", conn)

In [ ]:
pd.read_sql("""
SELECT Country_name, "Positive affect"
FROM happiness
GROUP BY
ORDER BY "Positive affect" DESC
LIMIT 10
""", conn)

In [ ]:
pd.read_sql("""
SELECT Country_name, Avg("Positive affect") AS " Avg Positive affect"
FROM happiness
GROUP BY Country_name
ORDER BY "Positive affect" DESC
LIMIT 10
""", conn)

**Top 10 Countries With Highest Negative Emotions**

In [ ]:
pd.read_sql("""
SELECT Country_name, AVG("Negative affect") "Avg Negative affect"
FROM happiness
GROUP BY Country_name
ORDER BY "Negative affect" DESC
LIMIT 10
""", conn)

**Correlational Analysis Of Happiness Score(Life Ladder)**

In this section, we analyze how different variables relate to the happiness score (Life Ladder).
Correlation helps us understand which factors are most strongly associated with happiness.

**The dataset includes several potential factors such as:**

Economic prosperity (Log GDP per capita)




*  Social relationships (Social_support)
*  Health (Healthy life expectancy at birth)
* Personal freedom (Freedom_to_make_life_choices)
* Emotional well-being (Positive affect / Negative affect)
* Trust in government (Confidence in national government)
* Corruption perception (Perceptions_of_corruption)

In [ ]:
# Select only numeric columns
numeric_df = df.select_dtypes(include='number')

# View the numeric columns
numeric_df.head()

In [ ]:
# Calculate correlations between all numeric variables
correlation_matrix = numeric_df.corr()

# Display the correlation matrix
correlation_matrix

In [ ]:
# Sort correlations with happiness
correlation_matrix["Life Ladder"].sort_values(ascending=False)

In [ ]:

sns.set_style("whitegrid")
plt.figure(figsize=(10,6))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    fmt=".2f",
    linewidths=0.5
)

plt.title("Feature Correlation Heatmap")
plt.show()

**Strong Positive Relationships**

   * Healthy life expectancy
   * Positive emotions
   * Social support

**Insight**: positive feelings, healthier countries with strong social support tend to be happier.

**Moderate Relationships**

   * Freedom to make life choices
   * Log GDP per capital

**Insight**: Personal freedom and Log GDP per capital also contribute to happiness.



**Negative Relationships**

   * Negative affect
   * Perceptions of corruption

**Insight**: Countries with more negative emotions and corruption tend to have lower happiness levels.